# Generated by Django 3.0.5 on 2020-04-10 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
