# Generated by Django 3.0.5 on 2020-04-10 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppapp', '0003_auto_20200410_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 14, 22, 24, 739298, tzinfo=utc)),
        ),
    ]
