# Generated by Django 3.0.5 on 2020-04-11 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppapp', '0004_auto_20200410_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('rank', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(default=None, upload_to='meal_pics/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 16, 59, 53, 35021, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to='shoppapp.User'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shoppapp.Location'),
        ),
    ]
