# Generated by Django 3.0.5 on 2020-04-11 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppapp', '0006_auto_20200411_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 17, 8, 50, 488880, tzinfo=utc)),
        ),
    ]
