# Generated by Django 3.0.5 on 2020-04-13 21:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shoppapp', '0008_auto_20200411_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 21, 39, 0, 120428, tzinfo=utc)),
        ),
    ]
